#自动调用api保活,无加密版
name: Auto Api

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
    branches: 
      - master
  schedule:
    - cron:   20/1 9,18 * * THU
    - cron:   1-20/1 10,19 * * THU
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests urllib re json base64 smtplib #安装requests等
      run: |
        pip install requests  urllib re json base64 smtplib
    - name: Test Api #Api调用
      run: |
        python index.py
        
