name: 宁蓓超星云签到

on: 
  release:
    types: [published]
#   push:
#     tags:
#     - 'v*'
#     branches: 
#       - master
  schedule:
    - cron:   20 1,10 * * 4
    - cron:   20 0 * * 6
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests #安装requests
      run: |
        pip install requests
    - name: 宁蓓云签到
      run: |
        python nb.py
        
